var city_database = [
{"Name":"Hohhot","id":201,"iso2":"CN"},
{"Name":"Heze","id":200,"iso2":"CN"},
{"Name":"Hengyang","id":199,"iso2":"CN"},
{"Name":"Hefei","id":198,"iso2":"CN"},
{"Name":"Hangzhou","id":197,"iso2":"CN"},
{"Name":"Handan","id":196,"iso2":"CN"},
{"Name":"Haerbin","id":195,"iso2":"CN"},
{"Name":"Guiyang","id":194,"iso2":"CN"},
{"Name":"Guilin","id":193,"iso2":"CN"},
{"Name":"Guangzhou","id":192,"iso2":"CN"},
{"Name":"Fuzhou","id":191,"iso2":"CN"},
{"Name":"Fuyang","id":190,"iso2":"CN"},
{"Name":"Fuxin","id":189,"iso2":"CN"},
{"Name":"Fushun","id":188,"iso2":"CN"},
{"Name":"Foshan","id":187,"iso2":"CN"},
{"Name":"Donguan","id":186,"iso2":"CN"},
{"Name":"Datong","id":185,"iso2":"CN"},
{"Name":"Daqing","id":184,"iso2":"CN"},
{"Name":"Dandong","id":183,"iso2":"CN"},
{"Name":"Dalian","id":182,"iso2":"CN"},
{"Name":"Chongqing","id":181,"iso2":"CN"},
{"Name":"Chifeng","id":180,"iso2":"CN"},
{"Name":"Chengdu","id":179,"iso2":"CN"},
{"Name":"Changzhou","id":178,"iso2":"CN"},
{"Name":"Changsha","id":177,"iso2":"CN"},
{"Name":"Changde","id":176,"iso2":"CN"},
{"Name":"Changchun","id":175,"iso2":"CN"},
{"Name":"Benxi","id":174,"iso2":"CN"},
{"Name":"Bengbu","id":173,"iso2":"CN"},
{"Name":"Beijing","id":172,"iso2":"CN"},
{"Name":"Baotou","id":171,"iso2":"CN"},
{"Name":"Baoding","id":170,"iso2":"CN"},
{"Name":"Anyang","id":169,"iso2":"CN"},
{"Name":"Anshun","id":168,"iso2":"CN"},
{"Name":"Anshan","id":167,"iso2":"CN"},
{"Name":"Valparaiso","id":166,"iso2":"CL"},
{"Name":"Santiago","id":165,"iso2":"CL"},
{"Name":"NDjamena","id":164,"iso2":"TD"},
{"Name":"Vancouver","id":163,"iso2":"CA"},
{"Name":"Toronto","id":162,"iso2":"CA"},
{"Name":"Gatineau","id":161,"iso2":"CA"},
{"Name":"Montreal","id":160,"iso2":"CA"},
{"Name":"Edmonton","id":159,"iso2":"CA"},
{"Name":"Calgary","id":158,"iso2":"CA"},
{"Name":"YaoundZ","id":157,"iso2":"CM"},
{"Name":"Douala","id":156,"iso2":"CM"},
{"Name":"Phnom Penh","id":155,"iso2":"KH"},
{"Name":"Ouagadougou","id":154,"iso2":"BF"},
{"Name":"Sofia","id":153,"iso2":"BG"},
{"Name":"Teresina","id":152,"iso2":"BR"},
{"Name":"Sao Paulo","id":151,"iso2":"BR"},
{"Name":"Salvador","id":150,"iso2":"BR"},
{"Name":"Rio de Janeiro","id":149,"iso2":"BR"},
{"Name":"Recife","id":148,"iso2":"BR"},
{"Name":"Porto Alegre","id":147,"iso2":"BR"},
{"Name":"Norte Nordeste Catarinense","id":146,"iso2":"BR"},
{"Name":"Natal","id":145,"iso2":"BR"},
{"Name":"Manaus","id":144,"iso2":"BR"},
{"Name":"Maceio","id":143,"iso2":"BR"},
{"Name":"Joao Pessoa","id":142,"iso2":"BR"},
{"Name":"Grande Vitoria","id":141,"iso2":"BR"},
{"Name":"Grand So Lus","id":140,"iso2":"BR"},
{"Name":"Goiana","id":139,"iso2":"BR"},
{"Name":"Fortaleza","id":138,"iso2":"BR"},
{"Name":"Florianopolis","id":137,"iso2":"BR"},
{"Name":"Curitiba","id":136,"iso2":"BR"},
{"Name":"Cuiaba","id":135,"iso2":"BR"},
{"Name":"Campo Grande","id":134,"iso2":"BR"},
{"Name":"Campinas","id":133,"iso2":"BR"},
{"Name":"Brasilia","id":132,"iso2":"BR"},
{"Name":"Belo Horizonte","id":131,"iso2":"BR"},
{"Name":"Belzm","id":130,"iso2":"BR"},
{"Name":"Baixada Santista","id":129,"iso2":"BR"},
{"Name":"Santa Cruz","id":128,"iso2":"BO"},
{"Name":"La Paz","id":127,"iso2":"BO"},
{"Name":"Cotonou","id":126,"iso2":"BJ"},
{"Name":"Brussels","id":125,"iso2":"BE"},
{"Name":"Antwerpen","id":124,"iso2":"BE"},
{"Name":"Minsk","id":123,"iso2":"BY"},
{"Name":"Rajshahi","id":122,"iso2":"BD"},
{"Name":"Khulna","id":121,"iso2":"BD"},
{"Name":"Dhaka","id":120,"iso2":"BD"},
{"Name":"Chittagong","id":119,"iso2":"BD"},
{"Name":"Baku","id":118,"iso2":"AZ"},
{"Name":"Sydney","id":117,"iso2":"AU"},
{"Name":"Perth","id":116,"iso2":"AU"},
{"Name":"Melbourne","id":115,"iso2":"AU"},
{"Name":"Brisbane","id":114,"iso2":"AU"},
{"Name":"Adelaide","id":113,"iso2":"AU"},
{"Name":"Yerevan","id":112,"iso2":"AM"},
{"Name":"San Miguel de Tucuman","id":111,"iso2":"AR"},
{"Name":"Rosario","id":110,"iso2":"AR"},
{"Name":"Mendoza","id":109,"iso2":"AR"},
{"Name":"Cordoba","id":108,"iso2":"AR"},
{"Name":"Buenos Aires","id":107,"iso2":"AR"},
{"Name":"Luanda","id":106,"iso2":"AO"},
{"Name":"Huambo","id":105,"iso2":"AO"},
{"Name":"Oran","id":104,"iso2":"DZ"},
{"Name":"Algiers","id":103,"iso2":"DZ"},
{"Name":"Huaian","id":202,"iso2":"CN"},
{"Name":"Huaibei","id":203,"iso2":"CN"},
{"Name":"Huainan","id":204,"iso2":"CN"},
{"Name":"Huzhou","id":205,"iso2":"CN"},
{"Name":"Jiamusi","id":206,"iso2":"CN"},
{"Name":"Jiaozuo","id":207,"iso2":"CN"},
{"Name":"Jiaxing","id":208,"iso2":"CN"},
{"Name":"Jilin","id":209,"iso2":"CN"},
{"Name":"Jinan","id":210,"iso2":"CN"},
{"Name":"Jining","id":211,"iso2":"CN"},
{"Name":"Jinxi","id":212,"iso2":"CN"},
{"Name":"Jinzhou","id":213,"iso2":"CN"},
{"Name":"Jixi","id":214,"iso2":"CN"},
{"Name":"Kaifeng","id":215,"iso2":"CN"},
{"Name":"Kaohsiung","id":216,"iso2":"CN"},
{"Name":"Kunming","id":217,"iso2":"CN"},
{"Name":"Langfang","id":218,"iso2":"CN"},
{"Name":"Lanzhou","id":219,"iso2":"CN"},
{"Name":"Leshan","id":220,"iso2":"CN"},
{"Name":"Lianyungang","id":221,"iso2":"CN"},
{"Name":"Liaoyang","id":222,"iso2":"CN"},
{"Name":"Linfen","id":223,"iso2":"CN"},
{"Name":"Linyi","id":224,"iso2":"CN"},
{"Name":"Liuan","id":225,"iso2":"CN"},
{"Name":"Liupanshui","id":226,"iso2":"CN"},
{"Name":"Liuzhou","id":227,"iso2":"CN"},
{"Name":"Luoyang","id":228,"iso2":"CN"},
{"Name":"Luzhou","id":229,"iso2":"CN"},
{"Name":"Mianyang","id":230,"iso2":"CN"},
{"Name":"Mudanjiang","id":231,"iso2":"CN"},
{"Name":"Nanchang","id":232,"iso2":"CN"},
{"Name":"Nanchong","id":233,"iso2":"CN"},
{"Name":"Nanjing","id":234,"iso2":"CN"},
{"Name":"Nanning","id":235,"iso2":"CN"},
{"Name":"Nantong","id":236,"iso2":"CN"},
{"Name":"Nanyang","id":237,"iso2":"CN"},
{"Name":"Neijiang","id":238,"iso2":"CN"},
{"Name":"Ningbo","id":239,"iso2":"CN"},
{"Name":"Pingdingshan","id":240,"iso2":"CN"},
{"Name":"Pingxiang","id":241,"iso2":"CN"},
{"Name":"Qingdao","id":242,"iso2":"CN"},
{"Name":"Qinhuangdao","id":243,"iso2":"CN"},
{"Name":"Qiqihaer","id":244,"iso2":"CN"},
{"Name":"Quanzhou","id":245,"iso2":"CN"},
{"Name":"Shanghai","id":246,"iso2":"CN"},
{"Name":"Shangqiu","id":247,"iso2":"CN"},
{"Name":"Shantou","id":248,"iso2":"CN"},
{"Name":"Shaoxing","id":249,"iso2":"CN"},
{"Name":"Shenyang","id":250,"iso2":"CN"},
{"Name":"Shenzhen","id":251,"iso2":"CN"},
{"Name":"Shijiazhuang","id":252,"iso2":"CN"},
{"Name":"Suining","id":253,"iso2":"CN"},
{"Name":"Suzhou","id":254,"iso2":"CN"},
{"Name":"Suzhou, Jiangsu","id":255,"iso2":"CN"},
{"Name":"Taian","id":256,"iso2":"CN"},
{"Name":"Taichung","id":257,"iso2":"CN"},
{"Name":"Tainan","id":258,"iso2":"CN"},
{"Name":"Taipei","id":259,"iso2":"CN"},
{"Name":"Taiyuan","id":260,"iso2":"CN"},
{"Name":"Tangshan","id":261,"iso2":"CN"},
{"Name":"Tianjin","id":262,"iso2":"CN"},
{"Name":"Tianmen","id":263,"iso2":"CN"},
{"Name":"Tianshui","id":264,"iso2":"CN"},
{"Name":"Tongliao","id":265,"iso2":"CN"},
{"Name":"Urumqi","id":266,"iso2":"CN"},
{"Name":"Weifang","id":267,"iso2":"CN"},
{"Name":"Wenzhou","id":268,"iso2":"CN"},
{"Name":"Wuhan","id":269,"iso2":"CN"},
{"Name":"Wuhu","id":270,"iso2":"CN"},
{"Name":"Wuxi","id":271,"iso2":"CN"},
{"Name":"Xiamen","id":272,"iso2":"CN"},
{"Name":"Xian","id":273,"iso2":"CN"},
{"Name":"Xiangfan","id":274,"iso2":"CN"},
{"Name":"Xiantao","id":275,"iso2":"CN"},
{"Name":"Xianyang","id":276,"iso2":"CN"},
{"Name":"Xingyi","id":277,"iso2":"CN"},
{"Name":"Xining","id":278,"iso2":"CN"},
{"Name":"Xinxiang","id":279,"iso2":"CN"},
{"Name":"Xinyang","id":280,"iso2":"CN"},
{"Name":"Xinyu","id":281,"iso2":"CN"},
{"Name":"Xuanzhou","id":282,"iso2":"CN"},
{"Name":"Xuzhou","id":283,"iso2":"CN"},
{"Name":"Yancheng","id":284,"iso2":"CN"},
{"Name":"Yantai","id":285,"iso2":"CN"},
{"Name":"Yibin","id":286,"iso2":"CN"},
{"Name":"Yichang","id":287,"iso2":"CN"},
{"Name":"Yichun","id":288,"iso2":"CN"},
{"Name":"Yichun","id":289,"iso2":"CN"},
{"Name":"Yinchuan","id":290,"iso2":"CN"},
{"Name":"Yingkou","id":291,"iso2":"CN"},
{"Name":"Yiyang","id":292,"iso2":"CN"},
{"Name":"Yongzhou","id":293,"iso2":"CN"},
{"Name":"Yuci","id":294,"iso2":"CN"},
{"Name":"Yueyang","id":295,"iso2":"CN"},
{"Name":"Yulin","id":296,"iso2":"CN"},
{"Name":"Zaozhuang","id":297,"iso2":"CN"},
{"Name":"Zhangjiakou","id":298,"iso2":"CN"},
{"Name":"Zhanjiang","id":299,"iso2":"CN"},
{"Name":"Zhaotong","id":300,"iso2":"CN"},
{"Name":"Zhengzhou","id":301,"iso2":"CN"},
{"Name":"Zhenjiang","id":302,"iso2":"CN"},
{"Name":"Zhuhai","id":303,"iso2":"CN"},
{"Name":"Zhuzhou","id":304,"iso2":"CN"},
{"Name":"Zibo","id":305,"iso2":"CN"},
{"Name":"Zigong","id":306,"iso2":"CN"},
{"Name":"Zunyi","id":307,"iso2":"CN"},
{"Name":"Barranquilla","id":308,"iso2":"CO"},
{"Name":"Bogota","id":309,"iso2":"CO"},
{"Name":"Bucaramanga","id":310,"iso2":"CO"},
{"Name":"Cali","id":311,"iso2":"CO"},
{"Name":"Cartagena","id":312,"iso2":"CO"},
{"Name":"Medellin","id":313,"iso2":"CO"},
{"Name":"Brazzaville","id":314,"iso2":"CD"},
{"Name":"San Jose","id":315,"iso2":"CR"},
{"Name":"Abidjan","id":316,"iso2":"CI"},
{"Name":"Havana","id":317,"iso2":"CU"},
{"Name":"Prague","id":318,"iso2":"CD"},
{"Name":"Kananga","id":319,"iso2":"CD"},
{"Name":"Kinshasa","id":320,"iso2":"CD"},
{"Name":"Lubumbashi","id":321,"iso2":"CD"},
{"Name":"Mbuji Mayi","id":322,"iso2":"CD"},
{"Name":"Copenhagen","id":323,"iso2":"DK"},
{"Name":"Santo Domingo","id":324,"iso2":"CD"},
{"Name":"Guayaquil","id":325,"iso2":"EC"},
{"Name":"Quito","id":326,"iso2":"EC"},
{"Name":"Alexandria","id":327,"iso2":"EG"},
{"Name":"Cairo","id":328,"iso2":"EG"},
{"Name":"San Salvador","id":329,"iso2":"SV"},
{"Name":"Addis Ababa","id":330,"iso2":"ET"},
{"Name":"Bordeaux","id":331,"iso2":"FR"},
{"Name":"Lille","id":332,"iso2":"FR"},
{"Name":"Lyon","id":333,"iso2":"FR"},
{"Name":"Marseille","id":334,"iso2":"FR"},
{"Name":"Nice","id":335,"iso2":"FR"},
{"Name":"Paris","id":336,"iso2":"FR"},
{"Name":"Toulouse","id":337,"iso2":"FR"},
{"Name":"Tbilisi","id":338,"iso2":"GE"},
{"Name":"Berlin","id":339,"iso2":"DE"},
{"Name":"Hamburg","id":340,"iso2":"DE"},
{"Name":"Colonge","id":341,"iso2":"DE"},
{"Name":"Munich","id":342,"iso2":"DE"},
{"Name":"Accra","id":343,"iso2":"GH"},
{"Name":"Kumasi","id":344,"iso2":"GH"},
{"Name":"Athens","id":345,"iso2":"GR"},
{"Name":"Thessaloniki","id":346,"iso2":"GR"},
{"Name":"Guatemala City","id":347,"iso2":"GT"},
{"Name":"Conakry","id":348,"iso2":"GN"},
{"Name":"Port au Prince","id":349,"iso2":"HT"},
{"Name":"Tegucigalpa","id":350,"iso2":"HN"},
{"Name":"Budapest","id":351,"iso2":"HU"},
{"Name":"Agra","id":352,"iso2":"IN"},
{"Name":"Ahmadabad","id":353,"iso2":"IN"},
{"Name":"Aligarh","id":354,"iso2":"IN"},
{"Name":"Allahabad","id":355,"iso2":"IN"},
{"Name":"Amritsar","id":356,"iso2":"IN"},
{"Name":"Asansol","id":357,"iso2":"IN"},
{"Name":"Aurangabad","id":358,"iso2":"IN"},
{"Name":"Bangalore","id":359,"iso2":"IN"},
{"Name":"Bareilly","id":360,"iso2":"IN"},
{"Name":"Bhiwandi","id":361,"iso2":"IN"},
{"Name":"Bhopal","id":362,"iso2":"IN"},
{"Name":"Bhubaneswar","id":363,"iso2":"IN"},
{"Name":"Chandigarh","id":364,"iso2":"IN"},
{"Name":"Madras","id":365,"iso2":"IN"},
{"Name":"Coimbatore","id":366,"iso2":"IN"},
{"Name":"Delhi","id":367,"iso2":"IN"},
{"Name":"Dhanbad","id":368,"iso2":"IN"},
{"Name":"Durg Bhilainagar","id":369,"iso2":"IN"},
{"Name":"Faridabad","id":370,"iso2":"IN"},
{"Name":"Ghaziabad","id":371,"iso2":"IN"},
{"Name":"Gauhati","id":372,"iso2":"IN"},
{"Name":"Gwalior","id":373,"iso2":"IN"},
{"Name":"Hubli","id":374,"iso2":"IN"},
{"Name":"Hyderabad","id":375,"iso2":"IN"},
{"Name":"Indore","id":376,"iso2":"IN"},
{"Name":"Jabalpur","id":377,"iso2":"IN"},
{"Name":"Jaipur","id":378,"iso2":"IN"},
{"Name":"Jalandhar","id":379,"iso2":"IN"},
{"Name":"Jammu","id":380,"iso2":"IN"},
{"Name":"Jamshedpur","id":381,"iso2":"IN"},
{"Name":"Jodhpur","id":382,"iso2":"IN"},
{"Name":"Kanpur","id":383,"iso2":"IN"},
{"Name":"Cochin","id":384,"iso2":"IN"},
{"Name":"Calcutta","id":385,"iso2":"IN"},
{"Name":"Kota","id":386,"iso2":"IN"},
{"Name":"Calicut","id":387,"iso2":"IN"},
{"Name":"Lucknow","id":388,"iso2":"IN"},
{"Name":"Ludhiana","id":389,"iso2":"IN"},
{"Name":"Madurai","id":390,"iso2":"IN"},
{"Name":"Meerut","id":391,"iso2":"IN"},
{"Name":"Moradabad","id":392,"iso2":"IN"},
{"Name":"Bombay","id":393,"iso2":"IN"},
{"Name":"Mysore","id":394,"iso2":"IN"},
{"Name":"Nagpur","id":395,"iso2":"IN"},
{"Name":"Nashik","id":396,"iso2":"IN"},
{"Name":"Patna","id":397,"iso2":"IN"},
{"Name":"Poona","id":398,"iso2":"IN"},
{"Name":"Raipur","id":399,"iso2":"IN"},
{"Name":"Rajkot","id":400,"iso2":"IN"},
{"Name":"Ranchi","id":401,"iso2":"IN"},
{"Name":"Salem","id":402,"iso2":"IN"},
{"Name":"Solapur","id":403,"iso2":"IN"},
{"Name":"Srinagar","id":404,"iso2":"IN"},
{"Name":"Surat","id":405,"iso2":"IN"},
{"Name":"Thiruvananthapuram","id":406,"iso2":"IN"},
{"Name":"Tiruchirappalli","id":407,"iso2":"IN"},
{"Name":"Vadodara","id":408,"iso2":"IN"},
{"Name":"Benares","id":409,"iso2":"IN"},
{"Name":"Vijayawada","id":410,"iso2":"IN"},
{"Name":"Visakhapatnam","id":411,"iso2":"IN"},
{"Name":"Bandar Lampung","id":412,"iso2":"ID"},
{"Name":"Bandung","id":413,"iso2":"ID"},
{"Name":"Bogor","id":414,"iso2":"ID"},
{"Name":"Jakarta","id":415,"iso2":"ID"},
{"Name":"Malang","id":416,"iso2":"ID"},
{"Name":"Medan","id":417,"iso2":"ID"},
{"Name":"Padang","id":418,"iso2":"ID"},
{"Name":"Palembang","id":419,"iso2":"ID"},
{"Name":"Pekan Baru","id":420,"iso2":"ID"},
{"Name":"Semarang","id":421,"iso2":"ID"},
{"Name":"Surabaya","id":422,"iso2":"ID"},
{"Name":"Ujung Pandang","id":423,"iso2":"ID"},
{"Name":"Ahvaz","id":424,"iso2":"IR"},
{"Name":"Esfahan","id":425,"iso2":"IR"},
{"Name":"Karaj","id":426,"iso2":"IR"},
{"Name":"Kermanshah","id":427,"iso2":"IR"},
{"Name":"Mashhad","id":428,"iso2":"IR"},
{"Name":"Qom","id":429,"iso2":"IR"},
{"Name":"Shiraz","id":430,"iso2":"IR"},
{"Name":"Tabriz","id":431,"iso2":"IR"},
{"Name":"Tehran","id":432,"iso2":"IR"},
{"Name":"Basra","id":433,"iso2":"IQ"},
{"Name":"Mosul","id":434,"iso2":"IQ"},
{"Name":"Baghdad","id":435,"iso2":"IQ"},
{"Name":"Erbil","id":436,"iso2":"IQ"},
{"Name":"Dublin","id":437,"iso2":"IE"},
{"Name":"Haifa","id":438,"iso2":"IL"},
{"Name":"Tel Aviv","id":439,"iso2":"IL"},
{"Name":"Milan","id":440,"iso2":"IT"},
{"Name":"Napels","id":441,"iso2":"IT"},
{"Name":"Palermo","id":442,"iso2":"IT"},
{"Name":"Rome","id":443,"iso2":"IT"},
{"Name":"Turin","id":444,"iso2":"IT"},
{"Name":"Kitakyushu","id":445,"iso2":"JP"},
{"Name":"Hiroshima","id":446,"iso2":"JP"},
{"Name":"Kyoto","id":447,"iso2":"JP"},
{"Name":"Nagoya","id":448,"iso2":"JP"},
{"Name":"Kobe","id":449,"iso2":"JP"},
{"Name":"Sapporo","id":450,"iso2":"JP"},
{"Name":"Sendai","id":451,"iso2":"JP"},
{"Name":"Tokyo","id":452,"iso2":"JP"},
{"Name":"Amman","id":453,"iso2":"JO"},
{"Name":"Almaty","id":454,"iso2":"KZ"},
{"Name":"Mombasa","id":455,"iso2":"KE"},
{"Name":"Nairobi","id":456,"iso2":"KE"},
{"Name":"Kuwait City","id":457,"iso2":"KW"},
{"Name":"Bishkek","id":458,"iso2":"KG"},
{"Name":"Beirut","id":459,"iso2":"LB"},
{"Name":"Monrovia","id":460,"iso2":"LR"},
{"Name":"Banghazi","id":461,"iso2":"LY"},
{"Name":"Tripoli","id":462,"iso2":"LY"},
{"Name":"Antananarivo","id":463,"iso2":"MG"},
{"Name":"Johore Bharu","id":464,"iso2":"MY"},
{"Name":"Klang","id":465,"iso2":"MY"},
{"Name":"Kuala Lumpur","id":466,"iso2":"MY"},
{"Name":"Bamako","id":467,"iso2":"ML"},
{"Name":"Aguascalientes","id":468,"iso2":"MX"},
{"Name":"Chihuahua","id":469,"iso2":"MX"},
{"Name":"Mexico City","id":470,"iso2":"MX"},
{"Name":"Ciudad Juarez","id":471,"iso2":"MX"},
{"Name":"Culiacan","id":472,"iso2":"MX"},
{"Name":"Guadalajara","id":473,"iso2":"MX"},
{"Name":"Leon de los Aldamas","id":474,"iso2":"MX"},
{"Name":"Mzrida","id":475,"iso2":"MX"},
{"Name":"Mexicali","id":476,"iso2":"MX"},
{"Name":"Monterrey","id":477,"iso2":"MX"},
{"Name":"Puebla","id":478,"iso2":"MX"},
{"Name":"QuerZtaro","id":479,"iso2":"MX"},
{"Name":"Saltillo","id":480,"iso2":"MX"},
{"Name":"San Luis Potosi","id":481,"iso2":"MX"},
{"Name":"Tijuana","id":482,"iso2":"MX"},
{"Name":"Toluca de Lerdo","id":483,"iso2":"MX"},
{"Name":"Mexico City","id":484,"iso2":"MX"},
{"Name":"Ulaanbaatar","id":485,"iso2":"MN"},
{"Name":"Casablanca","id":486,"iso2":"MA"},
{"Name":"Other cities/towns","id":487,"iso2":"AO"},
{"Name":"Djougou","id":488,"iso2":"BJ"},
{"Name":"Porto Novo","id":489,"iso2":"BJ"},
{"Name":"Other cities/towns","id":490,"iso2":"BJ"},
{"Name":"Autres villes","id":491,"iso2":"BF"},
{"Name":"Other cities/towns","id":492,"iso2":"BF"},
{"Name":"Bunjumbura","id":493,"iso2":"BI"},
{"Name":"Gitega","id":494,"iso2":"BI"},
{"Name":"Ngozi","id":495,"iso2":"BI"},
{"Name":"Other cities","id":496,"iso2":"BI"},
{"Name":"Younde","id":497,"iso2":"CM"},
{"Name":"Other cities/towns","id":498,"iso2":"CM"},
{"Name":"Yaounde","id":499,"iso2":"CM"},
{"Name":"Other cities","id":500,"iso2":"CM"},
{"Name":"Ndjamena","id":501,"iso2":"TD"},
{"Name":"Other cities/towns","id":502,"iso2":"TD"},
{"Name":"Moroni","id":503,"iso2":"KM"},
{"Name":"Other cities/towns","id":504,"iso2":"KM"},
{"Name":"Brazaville","id":505,"iso2":"CD"},
{"Name":"Other cities/towns","id":506,"iso2":"CD"},
{"Name":"Other cities/towns","id":507,"iso2":"CI"},
{"Name":"Havana","id":508,"iso2":"CU"},
{"Name":"Other cities","id":509,"iso2":"CU"},
{"Name":"Cairo","id":510,"iso2":"EG"},
{"Name":"Alexandria","id":511,"iso2":"EG"},
{"Name":"Port Said","id":512,"iso2":"EG"},
{"Name":"Suez","id":513,"iso2":"EG"},
{"Name":"Assiut","id":514,"iso2":"EG"},
{"Name":"Aswan","id":515,"iso2":"EG"},
{"Name":"Beni Suef","id":516,"iso2":"EG"},
{"Name":"Damietta","id":517,"iso2":"EG"},
{"Name":"Mansurah","id":518,"iso2":"EG"},
{"Name":"Kafr El Sheikh","id":519,"iso2":"EG"},
{"Name":"Tahta","id":520,"iso2":"EG"},
{"Name":"Damanhur","id":521,"iso2":"EG"},
{"Name":"Ismailia","id":522,"iso2":"EG"},
{"Name":"Giza","id":523,"iso2":"EG"},
{"Name":"Fayoum","id":524,"iso2":"EG"},
{"Name":"Sawhaj","id":525,"iso2":"EG"},
{"Name":"Qena","id":526,"iso2":"EG"},
{"Name":"Other cities/towns","id":527,"iso2":"EG"},
{"Name":"Ghurdqah","id":528,"iso2":"EG"},
{"Name":"Kharijah","id":529,"iso2":"EG"},
{"Name":"Nazret","id":530,"iso2":"ET"},
{"Name":"Other cities/towns","id":531,"iso2":"ET"},
{"Name":"Libreville","id":532,"iso2":"GA"},
{"Name":"Other cities/towns","id":533,"iso2":"GA"},
{"Name":"Banjul","id":534,"iso2":"GM"},
{"Name":"Other cities","id":535,"iso2":"GM"},
{"Name":"Other cities","id":536,"iso2":"GE"},
{"Name":"Other cities/towns","id":537,"iso2":"GH"},
{"Name":"Other cities","id":538,"iso2":"GH"},
{"Name":"Other cities/towns","id":539,"iso2":"GN"},
{"Name":"Other cities/towns","id":540,"iso2":"KE"},
{"Name":"Maseru","id":541,"iso2":"LS"},
{"Name":"Other cities/towns","id":542,"iso2":"LS"},
{"Name":"Other cities/towns","id":543,"iso2":"LR"},
{"Name":"Other cities/towns","id":544,"iso2":"MG"},
{"Name":"Lilongwe","id":545,"iso2":"MW"},
{"Name":"Other cities/towns","id":546,"iso2":"MW"},
{"Name":"Blantyre","id":547,"iso2":"MW"},
{"Name":"Mzuzu","id":548,"iso2":"MW"},
{"Name":"Other cities","id":549,"iso2":"MW"},
{"Name":"Other cities/towns","id":550,"iso2":"ML"},
{"Name":"Nouakchott","id":551,"iso2":"MR"},
{"Name":"Other cities/towns","id":552,"iso2":"MR"},
{"Name":"Other cities","id":553,"iso2":"MR"},
{"Name":"Casablanca","id":554,"iso2":"MA"},
{"Name":"Rabat","id":555,"iso2":"MA"},
{"Name":"Fes","id":556,"iso2":"MA"},
{"Name":"Marrakech","id":557,"iso2":"MA"},
{"Name":"Tangier","id":558,"iso2":"MA"},
{"Name":"Maknes","id":559,"iso2":"MA"},
{"Name":"Other cities/towns","id":560,"iso2":"MA"},
{"Name":"Maputo","id":561,"iso2":"MZ"},
{"Name":"Other cities/towns","id":562,"iso2":"MZ"},
{"Name":"Windhoek","id":563,"iso2":"NA"},
{"Name":"Other cities/towns","id":564,"iso2":"NA"},
{"Name":"Windhoek","id":565,"iso2":"NA"},
{"Name":"Niamey","id":566,"iso2":"NE"},
{"Name":"Other cities/towns","id":567,"iso2":"NE"},
{"Name":"Lagos","id":568,"iso2":"NG"},
{"Name":"Ibadan","id":569,"iso2":"NG"},
{"Name":"Ogbomosho","id":570,"iso2":"NG"},
{"Name":"Zaria","id":571,"iso2":"NG"},
{"Name":"Akure","id":572,"iso2":"NG"},
{"Name":"Oyo","id":573,"iso2":"NG"},
{"Name":"Effon","id":574,"iso2":"NG"},
{"Name":"Damaturu","id":575,"iso2":"NG"},
{"Name":"Owo","id":576,"iso2":"NG"},
{"Name":"Kano","id":577,"iso2":"NG"},
{"Name":"Abuja","id":578,"iso2":"NG"},
{"Name":"Other cities/towns","id":579,"iso2":"NG"},
{"Name":"kigali","id":580,"iso2":"RW"},
{"Name":"Other cities/towns","id":581,"iso2":"RW"},
{"Name":"Dakar","id":582,"iso2":"SN"},
{"Name":"Other cities/towns","id":583,"iso2":"SN"},
{"Name":"Freetown","id":584,"iso2":"SL"},
{"Name":"Other cities","id":585,"iso2":"SL"},
{"Name":"CapeTown","id":586,"iso2":"ZA"},
{"Name":"Durban","id":587,"iso2":"ZA"},
{"Name":"Pretoria","id":588,"iso2":"ZA"},
{"Name":"Port Elizabeth","id":589,"iso2":"ZA"},
{"Name":"West Rand","id":590,"iso2":"ZA"},
{"Name":"Other cities/towns","id":591,"iso2":"ZA"},
{"Name":"Mbabane","id":592,"iso2":"SZ"},
{"Name":"Manzini","id":593,"iso2":"SZ"},
{"Name":"Other cities/towns","id":594,"iso2":"SZ"},
{"Name":"Dar es Salaam","id":595,"iso2":"TZ"},
{"Name":"Arusha","id":596,"iso2":"TZ"},
{"Name":"Other cities/towns","id":597,"iso2":"TZ"},
{"Name":"Lome","id":598,"iso2":"TG"},
{"Name":"Other cities/towns","id":599,"iso2":"TG"},
{"Name":"Sokode","id":600,"iso2":"TG"},
{"Name":"Kara","id":601,"iso2":"TG"},
{"Name":"Other cities","id":602,"iso2":"TG"},
{"Name":"Kampala","id":603,"iso2":"UG"},
{"Name":"Other cities/towns","id":604,"iso2":"UG"},
{"Name":"Ndola","id":605,"iso2":"ZM"},
{"Name":"Chingola","id":606,"iso2":"ZM"},
{"Name":"Lusaka","id":607,"iso2":"ZM"},
{"Name":"Other cities/towns","id":608,"iso2":"ZM"},
{"Name":"Harare","id":609,"iso2":"ZW"},
{"Name":"Other cities/towns","id":610,"iso2":"ZW"},
{"Name":"Corazol","id":611,"iso2":"BZ"},
{"Name":"Orange walk","id":612,"iso2":"BZ"},
{"Name":"belize","id":613,"iso2":"BZ"},
{"Name":"San Ignacio","id":614,"iso2":"BZ"},
{"Name":"Punta Gorda","id":615,"iso2":"BZ"},
{"Name":"Other cities","id":616,"iso2":"BZ"},
{"Name":"Sucre","id":617,"iso2":"BO"},
{"Name":"Cochabamba","id":618,"iso2":"BO"},
{"Name":"Oruro","id":619,"iso2":"BO"},
{"Name":"Potosi","id":620,"iso2":"BO"},
{"Name":"Tarija","id":621,"iso2":"BO"},
{"Name":"Trinidad","id":622,"iso2":"BO"},
{"Name":"Cobija","id":623,"iso2":"BO"},
{"Name":"Windhoek","id":624,"iso2":"BR"},
{"Name":"Other cities/towns","id":625,"iso2":"BR"},
{"Name":"Sao Paulo","id":626,"iso2":"BR"},
{"Name":"Brasilia","id":627,"iso2":"BR"},
{"Name":"Goiana","id":628,"iso2":"BR"},
{"Name":"Victoria","id":629,"iso2":"BR"},
{"Name":"Bogota","id":630,"iso2":"CO"},
{"Name":"Neiva","id":631,"iso2":"CO"},
{"Name":"Valledupar","id":632,"iso2":"CO"},
{"Name":"Medellin","id":633,"iso2":"CO"},
{"Name":"Tunja","id":634,"iso2":"CO"},
{"Name":"Manizales","id":635,"iso2":"CO"},
{"Name":"Popayan","id":636,"iso2":"CO"},
{"Name":"Monteria","id":637,"iso2":"CO"},
{"Name":"Quibdo","id":638,"iso2":"CO"},
{"Name":"Riohacha","id":639,"iso2":"CO"},
{"Name":"Santa Marta","id":640,"iso2":"CO"},
{"Name":"Villavicencio","id":641,"iso2":"CO"},
{"Name":"Cucuta","id":642,"iso2":"CO"},
{"Name":"Armenia","id":643,"iso2":"CO"},
{"Name":"Pereira","id":644,"iso2":"CO"},
{"Name":"Sincelenjo","id":645,"iso2":"CO"},
{"Name":"Ibague","id":646,"iso2":"CO"},
{"Name":"Other cities/towns","id":647,"iso2":"CO"},
{"Name":"Florencia","id":648,"iso2":"CO"},
{"Name":"Arauca","id":649,"iso2":"CO"},
{"Name":"Yopali","id":650,"iso2":"CO"},
{"Name":"Mocoa","id":651,"iso2":"CO"},
{"Name":"San Anderes","id":652,"iso2":"CO"},
{"Name":"Leticia","id":653,"iso2":"CO"},
{"Name":"Puerto Inirida","id":654,"iso2":"CO"},
{"Name":"San Jose de Guaviare","id":655,"iso2":"CO"},
{"Name":"Mitu","id":656,"iso2":"CO"},
{"Name":"Puerto Carreno","id":657,"iso2":"CO"},
{"Name":"Azua","id":658,"iso2":"CD"},
{"Name":"Neiba","id":659,"iso2":"CD"},
{"Name":"Barahona","id":660,"iso2":"CD"},
{"Name":"Dajabon","id":661,"iso2":"CD"},
{"Name":"San Francisco de Macoris","id":662,"iso2":"CD"},
{"Name":"Comendador","id":663,"iso2":"CD"},
{"Name":"El Seibo","id":664,"iso2":"CD"},
{"Name":"Moca","id":665,"iso2":"CD"},
{"Name":"Jimani","id":666,"iso2":"CD"},
{"Name":"Higuey","id":667,"iso2":"CD"},
{"Name":"La Romana","id":668,"iso2":"CD"},
{"Name":"La Vega","id":669,"iso2":"CD"},
{"Name":"Nagua","id":670,"iso2":"CD"},
{"Name":"Monte Cristi","id":671,"iso2":"CD"},
{"Name":"Pedernales","id":672,"iso2":"CD"},
{"Name":"Bani","id":673,"iso2":"CD"},
{"Name":"Puerto Plata","id":674,"iso2":"CD"},
{"Name":"Salcedo","id":675,"iso2":"CD"},
{"Name":"Samana","id":676,"iso2":"CD"},
{"Name":"San Cristobal","id":677,"iso2":"CD"},
{"Name":"San Juan","id":678,"iso2":"CD"},
{"Name":"San Pedro de Macoris","id":679,"iso2":"CD"},
{"Name":"Cotui","id":680,"iso2":"CD"},
{"Name":"Santiago","id":681,"iso2":"CD"},
{"Name":"Sabaneta","id":682,"iso2":"CD"},
{"Name":"Mao","id":683,"iso2":"CD"},
{"Name":"Bonao","id":684,"iso2":"CD"},
{"Name":"Monte Plata","id":685,"iso2":"CD"},
{"Name":"Hato Mayor","id":686,"iso2":"CD"},
{"Name":"Guatemala city","id":687,"iso2":"GT"},
{"Name":"Guastatoya","id":688,"iso2":"GT"},
{"Name":"Antigua Guatemata","id":689,"iso2":"GT"},
{"Name":"Chimaltenango","id":690,"iso2":"GT"},
{"Name":"Escuintla","id":691,"iso2":"GT"},
{"Name":"Cuilapa","id":692,"iso2":"GT"},
{"Name":"Solol","id":693,"iso2":"GT"},
{"Name":"Totonicapan","id":694,"iso2":"GT"},
{"Name":"Quetzaltenango","id":695,"iso2":"GT"},
{"Name":"Mozatenago","id":696,"iso2":"GT"},
{"Name":"Retalhuleu","id":697,"iso2":"GT"},
{"Name":"San Marcos","id":698,"iso2":"GT"},
{"Name":"Huehuetenango","id":699,"iso2":"GT"},
{"Name":"Santa Cruz del Quinche","id":700,"iso2":"GT"},
{"Name":"Salama","id":701,"iso2":"GT"},
{"Name":"Coban","id":702,"iso2":"GT"},
{"Name":"Puerto Barrios","id":703,"iso2":"GT"},
{"Name":"Zacapa","id":704,"iso2":"GT"},
{"Name":"Chiquimula","id":705,"iso2":"GT"},
{"Name":"Jalapa","id":706,"iso2":"GT"},
{"Name":"Jutiapa","id":707,"iso2":"GT"},
{"Name":"Other cities/towns","id":708,"iso2":"GT"},
{"Name":"Other cities/towns","id":709,"iso2":"HT"},
{"Name":"Managua","id":710,"iso2":"NI"},
{"Name":"Jinotega","id":711,"iso2":"NI"},
{"Name":"Esteli","id":712,"iso2":"NI"},
{"Name":"Chinandega","id":713,"iso2":"NI"},
{"Name":"Leon","id":714,"iso2":"NI"},
{"Name":"Matagalpa","id":715,"iso2":"NI"},
{"Name":"Masaya","id":716,"iso2":"NI"},
{"Name":"Granada","id":717,"iso2":"NI"},
{"Name":"Other cities/towns","id":718,"iso2":"NI"},
{"Name":"Lima","id":719,"iso2":"PE"},
{"Name":"Trujillo","id":720,"iso2":"PE"},
{"Name":"Other cities/towns","id":721,"iso2":"PE"},
{"Name":"Chimbote","id":722,"iso2":"PE"},
{"Name":"Arequipa","id":723,"iso2":"PE"},
{"Name":"Cusco","id":724,"iso2":"PE"},
{"Name":"Huancayo","id":725,"iso2":"PE"},
{"Name":"Chiclayo","id":726,"iso2":"PE"},
{"Name":"Iquitos","id":727,"iso2":"PE"},
{"Name":"Piura","id":728,"iso2":"PE"},
{"Name":"Tacna","id":729,"iso2":"PE"},
{"Name":"Port of spain","id":730,"iso2":"TT"},
{"Name":"San Fernando","id":731,"iso2":"TT"},
{"Name":"Chaguanas","id":732,"iso2":"TT"},
{"Name":"Arima","id":733,"iso2":"TT"},
{"Name":"Other cities","id":734,"iso2":"TT"},
{"Name":"Tirana","id":735,"iso2":"AL"},
{"Name":"Other cities","id":736,"iso2":"AL"},
{"Name":"Ashtarak","id":737,"iso2":"AM"},
{"Name":"Artashat","id":738,"iso2":"AM"},
{"Name":"Armavil","id":739,"iso2":"AM"},
{"Name":"Gavar","id":740,"iso2":"AM"},
{"Name":"Vanadzor","id":741,"iso2":"AM"},
{"Name":"Hrazdan","id":742,"iso2":"AM"},
{"Name":"Gyumir","id":743,"iso2":"AM"},
{"Name":"Kapan","id":744,"iso2":"AM"},
{"Name":"Yegheknadzor","id":745,"iso2":"AM"},
{"Name":"Idjevan","id":746,"iso2":"AM"},
{"Name":"Other cities/towns","id":747,"iso2":"AM"},
{"Name":"Absheron","id":748,"iso2":"AZ"},
{"Name":"Agdash","id":749,"iso2":"AZ"},
{"Name":"Agjabedi","id":750,"iso2":"AZ"},
{"Name":"Agstafa","id":751,"iso2":"AZ"},
{"Name":"Ali Bayramli","id":752,"iso2":"AZ"},
{"Name":"Azizbeyov","id":753,"iso2":"AZ"},
{"Name":"Babek","id":754,"iso2":"AZ"},
{"Name":"Berde","id":755,"iso2":"AZ"},
{"Name":"Beylegan","id":756,"iso2":"AZ"},
{"Name":"Binagadi","id":757,"iso2":"AZ"},
{"Name":"Devechi","id":758,"iso2":"AZ"},
{"Name":"Gakh","id":759,"iso2":"AZ"},
{"Name":"Garadagh","id":760,"iso2":"AZ"},
{"Name":"Gedabey","id":761,"iso2":"AZ"},
{"Name":"Geychay","id":762,"iso2":"AZ"},
{"Name":"Goranboy","id":763,"iso2":"AZ"},
{"Name":"Gusar","id":764,"iso2":"AZ"},
{"Name":"Imishli","id":765,"iso2":"AZ"},
{"Name":"Ismayilli","id":766,"iso2":"AZ"},
{"Name":"Jalilabad","id":767,"iso2":"AZ"},
{"Name":"Kepez","id":768,"iso2":"AZ"},
{"Name":"Khachmaz","id":769,"iso2":"AZ"},
{"Name":"Khanlar","id":770,"iso2":"AZ"},
{"Name":"Khatai","id":771,"iso2":"AZ"},
{"Name":"Lankaran","id":772,"iso2":"AZ"},
{"Name":"Masally","id":773,"iso2":"AZ"},
{"Name":"Mingechevir","id":774,"iso2":"AZ"},
{"Name":"Nakhchivan","id":775,"iso2":"AZ"},
{"Name":"Narimanov","id":776,"iso2":"AZ"},
{"Name":"Nasimi","id":777,"iso2":"AZ"},
{"Name":"Nizami","id":778,"iso2":"AZ"},
{"Name":"Neftchala","id":779,"iso2":"AZ"},
{"Name":"Saatly","id":780,"iso2":"AZ"},
{"Name":"Sabail","id":781,"iso2":"AZ"},
{"Name":"Sabirabad","id":782,"iso2":"AZ"},
{"Name":"Sabunchu","id":783,"iso2":"AZ"},
{"Name":"Samakhy","id":784,"iso2":"AZ"},
{"Name":"Salyan","id":785,"iso2":"AZ"},
{"Name":"Shamkir","id":786,"iso2":"AZ"},
{"Name":"Sheki","id":787,"iso2":"AZ"},
{"Name":"Siyazan","id":788,"iso2":"AZ"},
{"Name":"Sumgait","id":789,"iso2":"AZ"},
{"Name":"Surakhany","id":790,"iso2":"AZ"},
{"Name":"Terter","id":791,"iso2":"AZ"},
{"Name":"Yevlakh","id":792,"iso2":"AZ"},
{"Name":"Yasamal","id":793,"iso2":"AZ"},
{"Name":"Zagatala","id":794,"iso2":"AZ"},
{"Name":"Zardab","id":795,"iso2":"AZ"},
{"Name":"Other cities","id":796,"iso2":"AZ"},
{"Name":"Ganja Gazakh","id":797,"iso2":"AZ"},
{"Name":"Shaki zaqatala","id":798,"iso2":"AZ"},
{"Name":"Guba Khachmaz","id":799,"iso2":"AZ"},
{"Name":"Aran","id":800,"iso2":"AZ"},
{"Name":"Yukhari Karabakh","id":801,"iso2":"AZ"},
{"Name":"Dakhlik Shirvan","id":802,"iso2":"AZ"},
{"Name":"Other cities/towns","id":803,"iso2":"BD"},
{"Name":"Barisal","id":804,"iso2":"BD"},
{"Name":"Sylhet","id":805,"iso2":"BD"},
{"Name":"Phnom penh","id":806,"iso2":"KH"},
{"Name":"Siem Reap","id":807,"iso2":"KH"},
{"Name":"Sisophon","id":808,"iso2":"KH"},
{"Name":"kampong Cham","id":809,"iso2":"KH"},
{"Name":"Kampong Speu","id":810,"iso2":"KH"},
{"Name":"Kampong Thum","id":811,"iso2":"KH"},
{"Name":"Ta Khmau","id":812,"iso2":"KH"},
{"Name":"Prey Veng","id":813,"iso2":"KH"},
{"Name":"Pursat","id":814,"iso2":"KH"},
{"Name":"Svay Rieng","id":815,"iso2":"KH"},
{"Name":"Takev","id":816,"iso2":"KH"},
{"Name":"Samraong","id":817,"iso2":"KH"},
{"Name":"Other cities/towns","id":818,"iso2":"KH"},
{"Name":"Kampong Chhnang","id":819,"iso2":"KH"},
{"Name":"Mumbai","id":820,"iso2":"IN"},
{"Name":"Kolkota","id":821,"iso2":"IN"},
{"Name":"New Delhi","id":822,"iso2":"IN"},
{"Name":"Hyberabad","id":823,"iso2":"IN"},
{"Name":"Pune","id":824,"iso2":"IN"},
{"Name":"Kochi","id":825,"iso2":"IN"},
{"Name":"Pondichery","id":826,"iso2":"IN"},
{"Name":"Akola","id":827,"iso2":"IN"},
{"Name":"Yamunanagar","id":828,"iso2":"IN"},
{"Name":"Kharagpur","id":829,"iso2":"IN"},
{"Name":"Hisar","id":830,"iso2":"IN"},
{"Name":"Agartala","id":831,"iso2":"IN"},
{"Name":"Gadag Betigeri","id":832,"iso2":"IN"},
{"Name":"Krishnanagar","id":833,"iso2":"IN"},
{"Name":"Other cities/towns","id":834,"iso2":"IN"},
{"Name":"Surabaja","id":835,"iso2":"ID"},
{"Name":"Surakarta","id":836,"iso2":"ID"},
{"Name":"Denpasar","id":837,"iso2":"ID"},
{"Name":"Jambi","id":838,"iso2":"ID"},
{"Name":"Purwokerto","id":839,"iso2":"ID"},
{"Name":"Kediri","id":840,"iso2":"ID"},
{"Name":"Palu","id":841,"iso2":"ID"},
{"Name":"Bitung","id":842,"iso2":"ID"},
{"Name":"Dumai","id":843,"iso2":"ID"},
{"Name":"Other cities/towns","id":844,"iso2":"ID"},
{"Name":"Jaya Pura","id":845,"iso2":"ID"},
{"Name":"Duhuk","id":846,"iso2":"IQ"},
{"Name":"Al Mawsil","id":847,"iso2":"IQ"},
{"Name":"Sulimania","id":848,"iso2":"IQ"},
{"Name":"Abril","id":849,"iso2":"IQ"},
{"Name":"Ramadi","id":850,"iso2":"IQ"},
{"Name":"Babil","id":851,"iso2":"IQ"},
{"Name":"Karbala","id":852,"iso2":"IQ"},
{"Name":"Wasit","id":853,"iso2":"IQ"},
{"Name":"Tikrit","id":854,"iso2":"IQ"},
{"Name":"Najaf","id":855,"iso2":"IQ"},
{"Name":"Samawah","id":856,"iso2":"IQ"},
{"Name":"Other cities","id":857,"iso2":"IQ"},
{"Name":"Balqa","id":858,"iso2":"JO"},
{"Name":"Zarqa","id":859,"iso2":"JO"},
{"Name":"Madaba","id":860,"iso2":"JO"},
{"Name":"Irbid","id":861,"iso2":"JO"},
{"Name":"Mafraq","id":862,"iso2":"JO"},
{"Name":"Jarash","id":863,"iso2":"JO"},
{"Name":"Ajlouon","id":864,"iso2":"JO"},
{"Name":"Karak","id":865,"iso2":"JO"},
{"Name":"Tafielah","id":866,"iso2":"JO"},
{"Name":"Maan","id":867,"iso2":"JO"},
{"Name":"Aqaba","id":868,"iso2":"JO"},
{"Name":"Other cities/towns","id":869,"iso2":"KZ"},
{"Name":"Shimkent","id":870,"iso2":"KZ"},
{"Name":"Zhezkazgan","id":871,"iso2":"KZ"},
{"Name":"Astana","id":872,"iso2":"KZ"},
{"Name":"Other cities","id":873,"iso2":"KZ"},
{"Name":"Chisinau","id":874,"iso2":"MD"},
{"Name":"Other cities/towns","id":875,"iso2":"MD"},
{"Name":"Ulaanmaatar","id":876,"iso2":"MN"},
{"Name":"Erdenet","id":877,"iso2":"MN"},
{"Name":"Darchan","id":878,"iso2":"MN"},
{"Name":"Other cities","id":879,"iso2":"MN"},
{"Name":"Kathmandu","id":880,"iso2":"NP"},
{"Name":"Other cities/towns","id":881,"iso2":"NP"},
{"Name":"Karachi","id":882,"iso2":"PK"},
{"Name":"Faisalabad","id":883,"iso2":"PK"},
{"Name":"Islamabad","id":884,"iso2":"PK"},
{"Name":"Other cities/towns","id":885,"iso2":"PK"},
{"Name":"Balochistan","id":886,"iso2":"PK"},
{"Name":"Metro Manila","id":887,"iso2":"PH"},
{"Name":"Cebu","id":888,"iso2":"PH"},
{"Name":"Cagayan","id":889,"iso2":"PH"},
{"Name":"Bacolod","id":890,"iso2":"PH"},
{"Name":"Other cities/towns","id":891,"iso2":"PH"},
{"Name":"Damascus","id":892,"iso2":"SY"},
{"Name":"Hims","id":893,"iso2":"SY"},
{"Name":"Hama","id":894,"iso2":"SY"},
{"Name":"Other cities","id":895,"iso2":"SY"},
{"Name":"Instabul","id":896,"iso2":"TR"},
{"Name":"Anakara","id":897,"iso2":"TR"},
{"Name":"Izmir","id":898,"iso2":"TR"},
{"Name":"Bursa","id":899,"iso2":"TR"},
{"Name":"Adana","id":900,"iso2":"TR"},
{"Name":"Gaziantep","id":901,"iso2":"TR"},
{"Name":"Karaman","id":902,"iso2":"TR"},
{"Name":"Antalya","id":903,"iso2":"TR"},
{"Name":"Other cities/towns","id":904,"iso2":"TR"},
{"Name":"Malatya","id":905,"iso2":"TR"},
{"Name":"Van","id":906,"iso2":"TR"},
{"Name":"Kirrikkale","id":907,"iso2":"TR"},
{"Name":"Aksaray","id":908,"iso2":"TR"},
{"Name":"Kyiv","id":909,"iso2":"UA"},
{"Name":"Dnipropetrovska","id":910,"iso2":"UA"},
{"Name":"Donecka","id":911,"iso2":"UA"},
{"Name":"Zaporizka","id":912,"iso2":"UA"},
{"Name":"Odeska","id":913,"iso2":"UA"},
{"Name":"Other cities","id":914,"iso2":"UA"},
{"Name":"AR Cremia","id":915,"iso2":"UA"},
{"Name":"Vinnytza","id":916,"iso2":"UA"},
{"Name":"Volyn","id":917,"iso2":"UA"},
{"Name":"Dniproprtrovsk","id":918,"iso2":"UA"},
{"Name":"Zhytomyr","id":919,"iso2":"UA"},
{"Name":"Uzhorod","id":920,"iso2":"UA"},
{"Name":"Zaporizhzhia","id":921,"iso2":"UA"},
{"Name":"Ivano Frankivsk","id":922,"iso2":"UA"},
{"Name":"Kirovohrad","id":923,"iso2":"UA"},
{"Name":"Luhansk","id":924,"iso2":"UA"},
{"Name":"Lviv","id":925,"iso2":"UA"},
{"Name":"Mikolayiv","id":926,"iso2":"UA"},
{"Name":"Odesa","id":927,"iso2":"UA"},
{"Name":"Poltava","id":928,"iso2":"UA"},
{"Name":"Rivne","id":929,"iso2":"UA"},
{"Name":"Sumy","id":930,"iso2":"UA"},
{"Name":"Ternopil","id":931,"iso2":"UA"},
{"Name":"Kharkiv","id":932,"iso2":"UA"},
{"Name":"Kherson","id":933,"iso2":"UA"},
{"Name":"Khmelnytskyi","id":934,"iso2":"UA"},
{"Name":"Cherkasy","id":935,"iso2":"UA"},
{"Name":"Chernivtsy","id":936,"iso2":"UA"},
{"Name":"Chernihiv","id":937,"iso2":"UA"},
{"Name":"Kyiv City","id":938,"iso2":"UA"},
{"Name":"City of Sevastopol","id":939,"iso2":"UA"},
{"Name":"Tashkent","id":940,"iso2":"UZ"},
{"Name":"Other cities/towns","id":941,"iso2":"UZ"},
{"Name":"Ho Chi Minh","id":942,"iso2":"VN"},
{"Name":"Ha Noi","id":943,"iso2":"VN"},
{"Name":"Hai Phong","id":944,"iso2":"VN"},
{"Name":"Other cities/towns","id":945,"iso2":"VN"},
{"Name":"Da Nang","id":946,"iso2":"VN"},
{"Name":"Sana'a","id":947,"iso2":"YE"},
{"Name":"Aden","id":948,"iso2":"YE"},
{"Name":"Taiz","id":949,"iso2":"YE"},
{"Name":"Other cities/towns","id":950,"iso2":"YE"},
{"Name":"Adan","id":951,"iso2":"YE"},
{"Name":"Ibb","id":952,"iso2":"YE"},
{"Name":"Other cities","id":953,"iso2":"YE"},
{"Name":"Brest","id":954,"iso2":"BY"},
{"Name":"Gomel","id":955,"iso2":"BY"},
{"Name":"Grodno","id":956,"iso2":"BY"},
{"Name":"Mogilev","id":957,"iso2":"BY"},
{"Name":"Vitebsk","id":958,"iso2":"BY"},
{"Name":"Other cities","id":959,"iso2":"BY"},
{"Name":"Tuzla","id":960,"iso2":"BA"},
{"Name":"Zenica","id":961,"iso2":"BA"},
{"Name":"Mostar","id":962,"iso2":"BA"},
{"Name":"Bihac","id":963,"iso2":"BA"},
{"Name":"Brocko","id":964,"iso2":"BA"},
{"Name":"Other cities","id":965,"iso2":"BA"},
{"Name":"Skopski","id":966,"iso2":"MK"},
{"Name":"Pelagonisk","id":967,"iso2":"MK"},
{"Name":"Vardarski","id":968,"iso2":"MK"},
{"Name":"Poloski","id":969,"iso2":"MK"},
{"Name":"Other cities","id":970,"iso2":"MK"},
{"Name":"Podgorica","id":971,"iso2":"ME"},
{"Name":"Other cities","id":972,"iso2":"ME"},
{"Name":"Belgrade","id":973,"iso2":"RS"},
{"Name":"Other cities","id":974,"iso2":"RS"},
{"Name":"Djouguo","id":975,"iso2":"BJ"},
{"Name":"Porto Novo","id":976,"iso2":"BJ"},
{"Name":"Cotunou","id":977,"iso2":"BJ"},
{"Name":"Njamena","id":978,"iso2":"TD"},
{"Name":"Karachi","id":979,"iso2":"PK"},
{"Name":" Sao Paulo","id":980,"iso2":"BR"},
{"Name":" Goiana","id":981,"iso2":"BR"},
{"Name":" Neiva:Huila","id":982,"iso2":"CO"},
{"Name":" Managua","id":983,"iso2":"NI"},
{"Name":" Lima","id":984,"iso2":"PE"},
{"Name":"Cotonuo","id":985,"iso2":"BJ"},
{"Name":"Other cities","id":986,"iso2":"BJ"},
{"Name":"Bangui","id":987,"iso2":"CD"},
{"Name":"Other cities","id":988,"iso2":"CD"},
{"Name":"Others cities/towns","id":989,"iso2":"GH"},
{"Name":"Others cities/towns","id":990,"iso2":"NG"},
{"Name":"Others","id":991,"iso2":"ZA"},
{"Name":"Others cities/towns","id":992,"iso2":"ZM"},
{"Name":"Other cities","id":993,"iso2":"ZM"},
{"Name":"Bulawayo","id":994,"iso2":"ZW"},
{"Name":"Other cities","id":995,"iso2":"ZW"},
{"Name":"Other cities/towns","id":996,"iso2":"BO"},
{"Name":"Other","id":997,"iso2":"CO"},
{"Name":"Medillin","id":998,"iso2":"CO"},
{"Name":"Dehli","id":999,"iso2":"IN"},
{"Name":"Chennai","id":1000,"iso2":"IN"},
{"Name":"Other cities/towns","id":1001,"iso2":"JO"},
{"Name":" Almaty","id":1002,"iso2":"KZ"},
{"Name":"Amsterdam","id":1003,"iso2":"NL"},
{"Name":"Rotterdam","id":1004,"iso2":"NL"},
{"Name":"Auckland","id":1005,"iso2":"NZ"},
{"Name":"Benin City","id":1006,"iso2":"NG"},
{"Name":"Ibadan","id":1007,"iso2":"NG"},
{"Name":"Ilorin","id":1008,"iso2":"NG"},
{"Name":"Kaduna","id":1009,"iso2":"NG"},
{"Name":"Lagos","id":1010,"iso2":"NG"},
{"Name":"Maiduguri","id":1011,"iso2":"NG"},
{"Name":"Ogbomosho","id":1012,"iso2":"NG"},
{"Name":"Port Harcourt","id":1013,"iso2":"NG"},
{"Name":"Zaria","id":1014,"iso2":"NG"},
{"Name":"Faisalabad","id":1015,"iso2":"PK"},
{"Name":"Gujranwala","id":1016,"iso2":"PK"},
{"Name":"Hyderabad","id":1017,"iso2":"PK"},
{"Name":"Karachi","id":1018,"iso2":"PK"},
{"Name":"Lahore","id":1019,"iso2":"PK"},
{"Name":"Multan","id":1020,"iso2":"PK"},
{"Name":"Peshawar","id":1021,"iso2":"PK"},
{"Name":"Quetta","id":1022,"iso2":"PK"},
{"Name":"Rawalpindi","id":1023,"iso2":"PK"},
{"Name":"Panama City","id":1024,"iso2":"PA"},
{"Name":"Asuncion","id":1025,"iso2":"PY"},
{"Name":"Davao","id":1026,"iso2":"PH"},
{"Name":"Manila","id":1027,"iso2":"PH"},
{"Name":"Zamboanga","id":1028,"iso2":"PH"},
{"Name":"Kracow","id":1029,"iso2":"PL"},
{"Name":"Lodz","id":1030,"iso2":"PL"},
{"Name":"Warsaw","id":1031,"iso2":"PL"},
{"Name":"Bucheon","id":1032,"iso2":"CD"},
{"Name":"Busan","id":1033,"iso2":"CD"},
{"Name":"Daegu","id":1034,"iso2":"CD"},
{"Name":"Daejon","id":1035,"iso2":"CD"},
{"Name":"Goyang","id":1036,"iso2":"CD"},
{"Name":"Gwangju","id":1037,"iso2":"CD"},
{"Name":"Incheon","id":1038,"iso2":"CD"},
{"Name":"Seongnam","id":1039,"iso2":"CD"},
{"Name":"Seoul","id":1040,"iso2":"CD"},
{"Name":"Suweon","id":1041,"iso2":"CD"},
{"Name":"Ulsan","id":1042,"iso2":"CD"},
{"Name":"Bucharest","id":1043,"iso2":"RO"},
{"Name":"Ad Dammam","id":1044,"iso2":"SA"},
{"Name":"Medina","id":1045,"iso2":"SA"},
{"Name":"Riyadh","id":1046,"iso2":"SA"},
{"Name":"Jiddah","id":1047,"iso2":"SA"},
{"Name":"Mecca","id":1048,"iso2":"SA"},
{"Name":"Belgrade","id":1049,"iso2":"RS"},
{"Name":"Mogadishu","id":1050,"iso2":"SO"},
{"Name":"Cape Town","id":1051,"iso2":"ZA"},
{"Name":"Ekurhuleni","id":1052,"iso2":"ZA"},
{"Name":"Johannesburg","id":1053,"iso2":"ZA"},
{"Name":"Vereeniging","id":1054,"iso2":"ZA"},
{"Name":"Barcelona","id":1055,"iso2":"ES"},
{"Name":"Madrid","id":1056,"iso2":"ES"},
{"Name":"Valencia","id":1057,"iso2":"ES"},
{"Name":"Khartoum","id":1058,"iso2":"SD"},
{"Name":"Zurich","id":1059,"iso2":"CH"},
{"Name":"Damascus","id":1060,"iso2":"CD"},
{"Name":"Aleppo","id":1061,"iso2":"CD"},
{"Name":"Homs","id":1062,"iso2":"CD"},
{"Name":"Bangkok","id":1063,"iso2":"TH"},
{"Name":"LomZ","id":1064,"iso2":"TG"},
{"Name":"Ankara","id":1065,"iso2":"TR"},
{"Name":"Istanbul","id":1066,"iso2":"TR"},
{"Name":"Konya","id":1067,"iso2":"TR"},
{"Name":"Dnipropetrovsk","id":1068,"iso2":"UA"},
{"Name":"Donetsk","id":1069,"iso2":"UA"},
{"Name":"Kiev","id":1070,"iso2":"UA"},
{"Name":"Zaporizhzhya","id":1071,"iso2":"UA"},
{"Name":"Dubai","id":1072,"iso2":"AE"},
{"Name":"Birmingham","id":1073,"iso2":"GB"},
{"Name":"Glasgow","id":1074,"iso2":"GB"},
{"Name":"Liverpool","id":1075,"iso2":"GB"},
{"Name":"London","id":1076,"iso2":"GB"},
{"Name":"Manchester","id":1077,"iso2":"GB"},
{"Name":"Newcastle upon Tyne","id":1078,"iso2":"GB"},
{"Name":"West Yorkshire","id":1079,"iso2":"GB"},
{"Name":"Atlanta","id":1080,"iso2":"US"},
{"Name":"Austin","id":1081,"iso2":"US"},
{"Name":"Baltimore","id":1082,"iso2":"US"},
{"Name":"Boston","id":1083,"iso2":"US"},
{"Name":"Bridgeport Stamford","id":1084,"iso2":"US"},
{"Name":"Buffalo","id":1085,"iso2":"US"},
{"Name":"Charlotte","id":1086,"iso2":"US"},
{"Name":"Chicago","id":1087,"iso2":"US"},
{"Name":"Cincinnati","id":1088,"iso2":"US"},
{"Name":"Cleveland","id":1089,"iso2":"US"},
{"Name":"Columbus","id":1090,"iso2":"US"},
{"Name":"Dallas","id":1091,"iso2":"US"},
{"Name":"Dayton","id":1092,"iso2":"US"},
{"Name":"Aurora","id":1093,"iso2":"US"},
{"Name":"Detroit","id":1094,"iso2":"US"},
{"Name":"El Paso","id":1095,"iso2":"US"},
{"Name":"Hartford","id":1096,"iso2":"US"},
{"Name":"Honolulu","id":1097,"iso2":"US"},
{"Name":"Houston","id":1098,"iso2":"US"},
{"Name":"Indianapolis","id":1099,"iso2":"US"},
{"Name":"Jacksonville","id":1100,"iso2":"US"},
{"Name":"Kansas City","id":1101,"iso2":"US"},
{"Name":"Las Vegas","id":1102,"iso2":"US"},
{"Name":"Los Angeles Long Beach Santa Ana","id":1103,"iso2":"US"},
{"Name":"Louisville","id":1104,"iso2":"US"},
{"Name":"Memphis","id":1105,"iso2":"US"},
{"Name":"Miami","id":1106,"iso2":"US"},
{"Name":"Milwaukee","id":1107,"iso2":"US"},
{"Name":"Minneapolis St Paul","id":1108,"iso2":"US"},
{"Name":"Nashville","id":1109,"iso2":"US"},
{"Name":"New Orleans","id":1110,"iso2":"US"},
{"Name":"Newark","id":1111,"iso2":"US"},
{"Name":"Oklahoma City","id":1112,"iso2":"US"},
{"Name":"Orlando","id":1113,"iso2":"US"},
{"Name":"Philadelphia","id":1114,"iso2":"US"},
{"Name":"Mesa","id":1115,"iso2":"US"},
{"Name":"Pittsburgh","id":1116,"iso2":"US"},
{"Name":"Portland","id":1117,"iso2":"US"},
{"Name":"Providence","id":1118,"iso2":"US"},
{"Name":"Richmond","id":1119,"iso2":"US"},
{"Name":"Bernardino","id":1120,"iso2":"US"},
{"Name":"Rochester","id":1121,"iso2":"US"},
{"Name":"Sacramento","id":1122,"iso2":"US"},
{"Name":"Salt Lake City","id":1123,"iso2":"US"},
{"Name":"San Antonio","id":1124,"iso2":"US"},
{"Name":"San Diego","id":1125,"iso2":"US"},
{"Name":"Oakland","id":1126,"iso2":"US"},
{"Name":"San Jose","id":1127,"iso2":"US"},
{"Name":"Seattle","id":1128,"iso2":"US"},
{"Name":"St. Louis","id":1129,"iso2":"US"},
{"Name":"St Petersburg","id":1130,"iso2":"US"},
{"Name":"Tucson","id":1131,"iso2":"US"},
{"Name":"Virginia Beach","id":1132,"iso2":"US"},
{"Name":"Washington, D.C.","id":1133,"iso2":"US"},
{"Name":"Montevideo","id":1134,"iso2":"UY"},
{"Name":"Barquisimeto","id":1135,"iso2":"IR"},
{"Name":"Caracas","id":1136,"iso2":"IR"},
{"Name":"Maracaibo","id":1137,"iso2":"IR"},
{"Name":"Maracay","id":1138,"iso2":"IR"},
{"Name":"Valencia","id":1139,"iso2":"IR"},
{"Name":"Hanoi","id":1140,"iso2":"VN"},
{"Name":"Hai Phong","id":1141,"iso2":"VN"},
{"Name":"Ho Chi  Minh City","id":1142,"iso2":"VN"},
{"Name":"Al Hudaydah","id":1143,"iso2":"YE"},
{"Name":"Sana a","id":1144,"iso2":"YE"},
{"Name":"Ta izz","id":1145,"iso2":"YE"},
{"Name":"Bangui","id":1146,"iso2":"TZ"},
{"Name":"Kinshasa","id":1147,"iso2":"LA"},
{"Name":"Other cities","id":1148,"iso2":"LA"},
{"Name":"Santo Domingo","id":1149,"iso2":"TZ"},
{"Name":"Brussels","id":1150,"iso2":"BE"},
{"Name":"Prague","id":1151,"iso2":"TZ"},
{"Name":"Copenhagen","id":1152,"iso2":"DK"},
{"Name":"Athens","id":1153,"iso2":"GR"},
{"Name":"Tegucigalapa","id":1154,"iso2":"HN"},
{"Name":"Milan","id":1155,"iso2":"IT"},
{"Name":"Mexico City","id":1156,"iso2":"MX"},
{"Name":"Kathmundu","id":1157,"iso2":"NP"},
{"Name":"Warsaw","id":1158,"iso2":"PL"},
{"Name":"Seoul","id":1159,"iso2":"TZ"},
{"Name":"Bucharest","id":1160,"iso2":"RO"},
{"Name":"Moscow","id":1161,"iso2":"RU"},
{"Name":"Zurich","id":1162,"iso2":"CH"},
{"Name":"Bangkok","id":1163,"iso2":"TH"},
{"Name":"New York","id":1164,"iso2":"US"}]